/* eslint-disable @typescript-eslint/explicit-function-return-type --
   These factories return Drizzle column builders whose inferred types are
   internal and impractical to annotate by hand; the types are inferred. */
import { integer, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Reusable column groups implementing the platform database conventions
 * (see docs/dna/05-database.md). Each helper returns *fresh* column builders so
 * they can be safely spread into multiple table definitions.
 */

/** UUID primary key, generated by PostgreSQL (`gen_random_uuid()`, core ≥ PG13). */
export function primaryKey() {
  return {
    id: uuid('id').primaryKey().defaultRandom(),
  };
}

/** UTC creation/modification timestamps (`TIMESTAMPTZ`). */
export function timestamps() {
  return {
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  };
}

/** Soft-delete marker (`NULL` = not deleted). */
export function softDelete() {
  return {
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  };
}

/** Audit actor references (nullable UUIDs; FK to users is added in a later phase). */
export function auditActors() {
  return {
    createdBy: uuid('created_by'),
    updatedBy: uuid('updated_by'),
    deletedBy: uuid('deleted_by'),
  };
}

/** Optimistic-locking version counter. */
export function versioning() {
  return {
    version: integer('version').notNull().default(1),
  };
}

/**
 * The full set of standard lifecycle/audit columns every business table should
 * include: id, timestamps, soft delete, audit actors, and version.
 */
export function baseColumns() {
  return {
    ...primaryKey(),
    ...timestamps(),
    ...softDelete(),
    ...auditActors(),
    ...versioning(),
  };
}
