export { createApiClient } from './client';
export type { ApiClientConfig } from './client';
export { ApiError, normalizeError } from './errors';
export { createAuthApi } from './auth';
export type {
  AuthApi,
  AuthUser,
  AuthenticatedUser,
  UserStatus,
  LoginInput,
  AuthSession,
  LoginResult,
  RefreshResult,
  ChangePasswordInput,
  UserPermissions,
  RegisterInput,
  RegisterResult,
  ResendVerificationResult,
  ForgotPasswordResult,
} from './auth';
export { createMembersApi } from './members';
export type {
  MembersApi,
  MemberStatus,
  MemberSummary,
  MemberDetail,
  MemberProfileData,
  MemberAddressData,
  MemberContactData,
  MemberNoteData,
  MemberDocumentData,
  MemberActivityData,
  MemberStatusHistoryData,
  PaginatedMembers,
  MemberSortField,
  ListMembersParams,
  MemberProfileInput,
  CreateMemberInput,
  UpdateMemberInput,
  ChangeStatusInput,
  AddNoteInput,
  AddDocumentInput,
  UpdateOwnProfileInput,
  GenerateDemoMembersResult,
  MemberAccountView,
  ChangeAccountStatusInput,
  AuthAccountStatus,
} from './members';
export { createWalletApi } from './wallet';
export type {
  WalletApi,
  WalletStatus,
  TransactionType,
  TransactionDirection,
  TransactionStatus,
  HoldStatus,
  WalletBalanceData,
  WalletSummary,
  WalletLimitData,
  WalletDetail,
  WalletTransactionData,
  WalletHoldData,
  WalletStatementData,
  BalanceValidationResult,
  PaginatedWallets,
  PaginatedTransactions,
  WalletSortField,
  ListWalletsParams,
  ListTransactionsParams,
  WalletLimitInput,
  CreateWalletInput,
  ChangeWalletStatusInput,
  AmountInput,
  AdjustmentInput,
  HoldInput,
  GenerateStatementInput,
} from './wallet';
export { createRewardsApi } from './rewards';
export type {
  RewardsApi,
  RewardProgramStatus,
  RewardRuleType,
  RewardTransactionType,
  RewardDirection,
  RewardTransactionStatus,
  RewardRedemptionStatus,
  RewardExpiryPolicy,
  RewardRuleData,
  RewardExpiryRuleData,
  RewardProgramSummary,
  RewardProgramDetail,
  MemberRewardBalance,
  RewardTransactionData,
  RewardRedemptionData,
  ExpiryRunResult,
  PaginatedPrograms,
  PaginatedRewardTransactions,
  RewardProgramSortField,
  ListProgramsParams,
  ListRewardTransactionsParams,
  MemberHistoryParams,
  RewardRuleInput,
  CreateProgramInput as CreateRewardProgramInput,
  UpdateProgramInput as UpdateRewardProgramInput,
  ChangeProgramStatusInput as ChangeRewardProgramStatusInput,
  AllocateInput,
  RedeemInput,
  RewardAdjustInput,
} from './rewards';
export { createCampaignsApi } from './campaigns';
export type {
  CampaignsApi,
  CampaignStatus,
  CampaignType,
  CampaignAudienceType,
  CampaignRuleType,
  CampaignScheduleType,
  CampaignMemberStatus,
  CampaignExecutionStatus,
  CampaignRuleData,
  CampaignRewardData,
  CampaignScheduleData,
  CampaignEnrollmentStats,
  CampaignSummary,
  CampaignDetail,
  CampaignEnrollmentData,
  CampaignHistoryData,
  CampaignExecutionData,
  MemberCampaignView,
  PaginatedCampaigns,
  PaginatedEnrollments,
  CampaignSortField,
  ListCampaignsParams,
  ListEnrollmentsParams,
  CampaignRuleInput,
  CampaignRewardInput,
  CreateCampaignInput,
  UpdateCampaignInput,
  ChangeCampaignStatusInput,
  ScheduleCampaignInput,
  AddTargetsInput,
  ExecuteCampaignInput,
} from './campaigns';
export { createNotificationsApi } from './notifications';
export type {
  NotificationsApi,
  NotificationChannel,
  NotificationStatus,
  NotificationQueueStatus,
  NotificationDeliveryResult,
  TemplateStatus,
  InboxFilter,
  TemplateData as NotificationTemplateData,
  TemplatePreview,
  NotificationData,
  QueueItemData,
  DeliveryData,
  NotificationLogData,
  PreferenceData,
  QueueRunResult,
  PaginatedTemplates,
  PaginatedNotifications,
  TemplateSortField,
  ListTemplatesParams,
  ListNotificationsParams,
  InboxParams,
  CreateTemplateInput,
  UpdateTemplateInput,
  TemplateVariables,
  SendNotificationInput,
  PreferenceInput,
} from './notifications';
export { createReportsApi } from './reports';
export type {
  ReportsApi,
  ReportFormat,
  ScheduleFrequency,
  JobStatus as ReportJobStatus,
  WidgetType as ReportWidgetType,
  ReportCell,
  ReportRow,
  ReportColumn,
  ReportFilters,
  ReportResult,
  ReportCategoryData,
  ReportDefinitionData,
  ReportExportData,
  ReportScheduleData,
  ReportExecutionData,
  DashboardWidgetData,
  DashboardLayoutItem,
  DashboardKpis,
  RecentActivityItem,
  DashboardData,
  SavedReportData,
  SavedFilterData,
  FavoriteReportData,
  MemberWalletSummary as ReportMemberWalletSummary,
  MemberRewardSummary as ReportMemberRewardSummary,
  Paginated as ReportPaginated,
  ReportSortField,
  ListReportsParams,
  ListExportsParams,
  ListHistoryParams,
  RunReportInput,
  CreateExportInput,
  CreateScheduleInput,
  UpdateScheduleInput,
  SaveReportInput,
  SaveFilterInput,
} from './reports';
export { createSettingsApi } from './settings';
export type {
  SettingsApi,
  SettingValueType,
  SettingData,
  SettingCategoryData,
  SettingHistoryData,
  FeatureToggleData,
  MaintenanceWindowData,
  MaintenanceStatus,
  PublicSettings,
  SettingsPaginated,
  ListSettingsParams,
  SettingsHistoryParams,
  UpdateSettingsInput,
  UpdateBrandingInput,
  CreateFeatureToggleInput,
  UpdateFeatureToggleInput,
  MaintenanceInput,
} from './settings';
export { createDreamStoreApi } from './dream-store';
export type {
  DreamStoreApi,
  ProductStatus,
  OrderStatus as StoreOrderStatus,
  StockStatus,
  InventoryChangeType,
  StoreCategory,
  StoreProduct,
  StoreOrderItem,
  StoreOrder,
  StoreInventoryHistory,
  StoreRedeemResult,
  PaginatedProducts,
  PaginatedStoreOrders,
  ProductSortField,
  ListProductsParams,
  ListInventoryParams,
  ListStoreOrdersParams,
  CreateProductInput,
  UpdateProductInput,
  AdjustStockInput,
  CreateCategoryInput,
  UpdateCategoryInput,
  StoreRedeemInput,
} from './dream-store';
export { createGamesApi } from './games';
export type {
  GamesApi,
  GameStatus,
  GameSessionStatus,
  Game,
  GameSession,
  GamePlayResult,
  GameScoreResult,
  GameHistoryItem,
  PaginatedGameHistory,
  GameHistoryParams,
} from './games';
